# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.hostname = "csgo-local"
  config.vm.network "public_network", bridge: "Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC" 
  config.vm.synced_folder "~/", "/host/"

  config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
    vb.memory = "512"
    vb.cpus = "1"
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum check-update
    yum install -y epel-release 
    yum update -y
    yum install -y ansible
  SHELL

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/vagrant/provision.yml"
    ansible.limit = "all"
    ansible.verbose = "v"
  end
end
