- hosts: all
  become: yes
  tasks:
  - name: Update /etc/hosts
    blockinfile:
      path: '/etc/hosts'
      block: |
        10.7.9.118          release.sjc.host.com
        10.5.82.241         release.atl.host.com
        10.10.82.10         release.pdx.host.com
        10.30.82.10         release.iad.host.com
        10.5.133.21         release.dca.host.com
        10.5.80.77          lbl553.atl.host.com
        10.5.80.87          lbl554.atl.host.com
        10.7.80.24          lbl701a.sjc.host.com
        10.7.80.23          lbl702b.sjc.host.com
        205.189.102.246     panvpn.host.com
        10.7.82.72          lbl721.sjc.host.com
        10.7.83.60          mgt718.sjc.host.com
        10.7.82.249         lbl730.sjc.host.com
        10.7.82.250         lbl731.sjc.host.com
  
  - name: Create ssh config folder
    file:
      path: /home/vagrant/.ssh
      state: directory

  - name: Create ssh config file
    file: 
      path: /home/vagrant/.ssh/config
      state: touch

  - name: Update SSH config file
    blockinfile:
      path: '/home/vagrant/.ssh/config'
      block: |
        Host release.*.host.com
          User REPLACE-WITH-USERNAME
        Host mgt*.*.host.com
          User REPLACE-WITH-USERNAME
          
  - name: Install GlobalProtect vpn client
    yum: 
      name: /home/vagrant/host-files/GlobalProtect_rpm-5.0.5.0-11.rpm
      state: present
