# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "viva-la-resistance"
  #config.vm.network "public_network", bridge: "eth0"
  config.vm.network "public_network", bridge: "Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC" 
  config.vm.synced_folder "~/Downloads/", "/host/downloads/"
  config.vm.synced_folder "~/Dropbox/", "/host/dropbox/"

  config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
     vb.memory = "512"
     vb.cpus = "2"
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum check-update
    yum install -y epel-release
    yum update -y
    yum groupinstall -y 'Development Tools'
    yum install -y git jq wget vim curl nmap bind-utils htop tmux python3
  SHELL
end
